### ISSUE TITLE
Update of Bavaria-quebec dataset

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/ms-lesion-agnostic#17]
Opening this issue to discuss the new modifications made to the Bavaria-quebec dataset and how they could be of interest in the case of the ms-lesion-agnostic model. 

Tagging @naga-karthik

**Comment by naga-karthik** [comment]
Absolutely! there are two datasets from the bavaria group: 

1. `bavaria-quebec-spine-ms-unstitched`: contains the unstitched, individual chunks of axial T2w images with both lesion and SC seg masks. This is the new dataset with manual segmentations by 2 radiologists I believe from TUM 
2. `bavaria-quebec-spine-ms`: contains the stitched, whole-spine images with both lesion and SC segmentation masks. The chunks were stitched together and then re-corrected by the 2 radiologists in this new version of the dataset

I believe for the `ms-lesion-agnostic` project, the chunks dataset could be a good addition as the image sizes are smaller than the whole spine images. Both the above datasets are yet to be merged to `master` by but I believe the chunks version is good as it is in its current branch and be used at the moment. 

Git-annex info: 

1. Unstitched (i.e. chunks) -- `datasets/bavaria-quebec-spine-ms-unstitched/src/branch/mgp/jqmcginnis-20240513`
2. Stitched -- `datasets/bavaria-quebec-spine-ms/src/branch/mgp/jqmcginnis-20240513`

**Comment by plbenveniste** [comment]
@naga-karthik Will new modifications be done to the dataset soon ? Or can I close this issue ?

**Comment by naga-karthik** [comment]
I don't think there are any more modifications to be done to the dataset at least in the near future. so I believe it can be merged to master and this issue can be closed

**Comment by plbenveniste** [comment]
Thanks @naga-karthik for your answer ! 

@mguaypaq I can't open a PR (I think that's because I am not the creator of the branch) for the two related bavaria datasets. Could you do it ? Just so that it doesn't fall into oblivion...

**Comment by mguaypaq** [comment]
Oh, I see why we can't open pull requests: it's because the new commit is in a branch that's unrelated to `master` (they don't have the same root commit in git). I did it this way because the new data is not an evolution of the previous dataset, but a new dataset entirely (they don't even have the same set of subjects).

I'll create some new branches from `master` with the new dataset so that we can compare them anyway.

**Comment by mguaypaq** [comment]
Here are the pull requests:
https://data.neuro.polymtl.ca/datasets/bavaria-quebec-spine-ms/pulls/1
https://data.neuro.polymtl.ca/datasets/bavaria-quebec-spine-ms-unstitched/pulls/1

The previous version had a CHANGELOG file with the following version numbers and dates:
  - 1.0.0 2022-10-12
  - 1.0.1 2022-10-21
  - 1.0.2 2022-11-02
  - 1.1.0 2023-04-25

But the new version from 2024-05-13 lists itself as version 1.0.0, which is inconsistent. Should I just call it version 1.2.0? Or maybe 2.0.0, since it's a very different set of subjects?

**Comment by plbenveniste** [comment]
I would go for 2.0.0. but I think that @naga-karthik is more familiar with this dataset then I am. 

Regarding the changelog of the new data we could just add in the README that the segmentations were corrected and a new batch of data was sent on the 2024-05-13. Would that work ?

**Comment by naga-karthik** [comment]
Hello! 

> Or maybe 2.0.0, since it's a very different set of subjects?

Agree with this. Likely, the dataset won't be updated again in the near future so we can stick with 2.0.0

> Also, the new version just has no changelog, what should go in there for this version?

Agree with PL's suggestion of mentioning the date. Looking at the json sidecars, we have names of the raters from the Bavaria team as well. We can possibly add those too in case we need to contact the team/person in the future! 

<details>
<summary> json sidecar info </summary>

```
{
    "GeneratedBy": [
        {
            "Author": "generated by custom 3D nnUNet",
            "Date": "2023-10-24"
        },
        {
            "Author": "Ricarda Wurm, Sebastian Ruehling, Julian McGinnis",
            "Date": "2023-11-06"
        }
    ]
}
```

</details>

**Comment by mguaypaq** [comment]
Done!

**Comment by plbenveniste** [comment]
Thanks @mguaypaq ! Closing this issue then !
